# Auto-generated by Wire Framework — agentic_data_stack / lookml_views phase 2026-06-06
# New canonical model created in canonical_models phase — no prior LookML view existed.
# Grain: one row per Wire Framework command invocation.
# Canonical source for: wire_commands_total, autopilot_run_count, wire_active_users_weekly.

view: agentic_framework_command_events_fact {
  sql_table_name: `ra-development.analytics.agentic_framework_command_events_fact` ;;

  # ── Primary Key ───────────────────────────────────────────────────
  dimension: event_pk {
    primary_key: yes
    hidden: yes
    type: string
    sql: ${TABLE}.event_pk ;;
  }

  # ── Foreign Keys ──────────────────────────────────────────────────
  dimension: consultant_fk {
    hidden: yes
    type: string
    sql: ${TABLE}.consultant_fk ;;
  }

  dimension: project_fk {
    hidden: yes
    type: string
    sql: ${TABLE}.project_fk ;;
  }

  # ── Timestamp ─────────────────────────────────────────────────────
  dimension_group: event {
    type: time
    timeframes: [raw, date, week, week_of_year, month, month_num, quarter, year]
    datatype: datetime
    sql: ${TABLE}.event_ts ;;
    label: "Event"
    description: "Timestamp of the Wire Framework command invocation."
  }

  # ── Dimensions ────────────────────────────────────────────────────
  dimension: command_name {
    type: string
    sql: ${TABLE}.command_name ;;
    label: "Command Name"
    description: "Wire command identifier, e.g. 'requirements-generate', 'semantic_layer-validate', 'autopilot'."
  }

  dimension: artifact_type {
    type: string
    sql: ${TABLE}.artifact_type ;;
    label: "Artifact Type"
    description: "High-level artifact category derived from command_name prefix: requirements, design, development, testing, deployment, enablement, utility."
  }

  dimension: exit_status {
    type: string
    sql: ${TABLE}.exit_status ;;
    label: "Exit Status"
    description: "Command outcome: success, error, or cancelled."
  }

  dimension: release_label {
    type: string
    sql: ${TABLE}.release_label ;;
    label: "Release Label"
    description: "Wire release identifier this command was run against, e.g. '01-ra-agentic-analytics'."
  }

  dimension: project_id {
    type: string
    sql: ${TABLE}.project_id ;;
    label: "Project ID"
    description: "Wire project ID in YYYYMMDD_client_type format."
  }

  # ── Canonical semantic layer measures — Wire agentic_data_stack 2026-06-06 ────────────

  measure: wire_commands_total {
    group_label: "Canonical Metrics"
    label: "Wire Commands (Total)"
    type: count
    sql: ${TABLE}.event_pk ;;
    description: "Count of all Wire Framework command invocations. Includes all exit statuses."
  }

  measure: wire_commands_successful {
    group_label: "Canonical Metrics"
    label: "Wire Commands (Successful)"
    type: count
    sql: CASE WHEN ${TABLE}.exit_status = 'success' THEN ${TABLE}.event_pk END ;;
    description: "Count of Wire commands that completed with exit_status = 'success'."
  }

  measure: wire_command_success_rate {
    group_label: "Canonical Metrics"
    label: "Wire Command Success Rate"
    type: number
    sql: SAFE_DIVIDE(${wire_commands_successful}, NULLIF(${wire_commands_total}, 0)) ;;
    value_format_name: percent_1
    description: "Proportion of Wire commands completing successfully."
  }

  measure: wire_active_consultants {
    group_label: "Canonical Metrics"
    label: "Wire Active Consultants"
    type: count_distinct
    sql: ${TABLE}.consultant_fk ;;
    description: "Count of distinct consultants who ran at least one Wire command in the period."
  }

}
